name: Docker Build & Run

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t python-parser .

      - name: Run parser
        run: docker run --rm python-parser